config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:update]
  resources :friendships, only: %i[create update destroy]
  resources :posts
  resources :comments

  put '/like' => 'likes#create'
  delete '/like' => 'likes#destroy'

  get '/:username' => 'users#show', :constrain => { username: /[a-zA-Z-]+/ }, as: 'username'

  get '/me/:username' => 'users#index', :constrain => { username: /[a-zA-Z-]+/ }, as: 'user_home'
  put '/me/:username' => 'users#update'

  get '/home/search' => 'search#index', as: 'search'

  get 'home/notifications' => 'search#show', as: 'notifications'
  get ':username/post/:id/edit' => 'posts#edit', as: 'post_edit'

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @people = params[:search] ? @user.search(params[:search].downcase) : @user.all_users

    @people = @user.blocked if params[:search] == 'blockeds'
    @people = @user.all_users true if params[:search] == 'friends'
  end

  def show
    @user = current_user
    @people = @user.pending
  end

  private

  def search_params
    param.require(:search).permit(:search)
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/search/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
    <%=text_field_tag :search, params[:search], placeholder: "Search by Username... Or try typing 'friends' or 'blockeds'", autocomplete: 'off'%>
    <%=button_tag :icon, name: nil do %>
        <i class="material-icons">search</i>
    <% end %>
    <%submit_tag "", name:nil%>
<% end %>
  

app/views/search/index.html.erb
<!-- SEARCH PEOPLE FOR BLOCKING AND SENDING FRIENDSHIP NOTIFICATION -->

<div class="search-bar">
    <%= render 'search'%>
</div>
    
<main class="people">
    <%= render @people %>
    <% if @people == [] %>
        <div class="not-found">
            <i>Who?<br>Perhaps you misspelled</i>
        </div>
<% end %>
</main>

app/views/search/show.html.erb
<!-- ACCEPT FRIENSHIP LINKS -->
<main class="people notification-add">
    <% @people.each do |person| %>
        <div class="person">
            <div class="person-links">
                <%=link_to image_tag(person.profile_pic.url), username_path(person.username)%>
                <h1><%= person.username.capitalize%></h1>
            </div>
            <div class="accept-links">

                <%= link_to friendship_path(id: person.friendship_id, status: "friends"), method: :put , class:'accept-friendship' do %>
                    <i class="material-icons">check</i>
                <% end %>

                <%= link_to friendship_path(person.friendship_id), method: :delete,  class: "reject" do %>
                    <i class="material-icons">close</i>
                <% end %>

            </div>
        </div>
    <% end %>
    <% if @people == [] %>
        <div class="cero-notification-message">
            <i>Nothing to see here pal...</i>
        </div>
    <% end %>
</main>