config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:update]
  resources :friendships, only: %i[create update destroy]
  resources :posts
  resources :comments

  put '/like' => 'likes#create'
  delete '/like' => 'likes#destroy'

  get '/:username' => 'users#show', :constrain => { username: /[a-zA-Z-]+/ }, as: 'username'

  get '/me/:username' => 'users#index', :constrain => { username: /[a-zA-Z-]+/ }, as: 'user_home'
  put '/me/:username' => 'users#update'

  get '/home/search' => 'search#index', as: 'search'

  get 'home/notifications' => 'search#show', as: 'notifications'
  get ':username/post/:id/edit' => 'posts#edit', as: 'post_edit'

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save { email.downcase! }
  before_save { username.downcase! }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { maximum: 30 }

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_attached_file :profile_pic,
                    storage: :cloudinary,
                    path: 'roleanding/users/:id/:username/:filename',
                    cloudinary_credentials: Rails.root.join('config/cloudinary.yml')

  validates_attachment_content_type :profile_pic, content_type: %r{\Aimage/.*\z}

  def self.new_with_session(params, session)
    if session['devise.facebook_data']
      new(session['devise.facebook_data'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name # assuming the user model has a name
    end
  end

  def are_we_friends?(other_user_id)
    are_we = friendships.where(friend_id: other_user_id).exists?
    are_we ||= inverse_friendships.where(user_id: other_user_id).exists?
    are_we
  end

  def blocked?(other_user_id)
    blocked = self.blocked.any? { |blocked_person| blocked_person.id == other_user_id }
    block_by = blocked_me.any? { |blocked_from| blocked_from.id == other_user_id }
    (blocked = blocked) || block_by
  end

  def all_users(friends_only = false)
    all_users = []
    sql = "SELECT u.id, u.username, u.profile_pic_file_name
           FROM users u
           WHERE u.id != #{id}
           AND NOT EXISTS(SELECT friendships.id
                          FROM friendships
                          WHERE (friendships.user_id = #{id}
                                 AND friendships.friend_id = u.id)
                                 OR (friendships.friend_id = #{id}
                                 AND friendships.user_id = u.id))"
    unexisting_friendships = User.find_by_sql(sql) unless friends_only

    sql = "SELECT u.id, u.username, u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u JOIN friendships f ON (f.user_id = #{id}
                                               AND f.friend_id = u.id)
                                               OR (f.friend_id = #{id}
                                               AND f.user_id = u.id)
           WHERE u.id != #{id}
           AND EXISTS(SELECT friendships.id FROM friendships
               WHERE (friendships.user_id = #{id}
                      AND friendships.friend_id = u.id)
                      OR (friendships.friend_id = #{id}
                      AND friendships.user_id = u.id))
           AND CASE
           WHEN f.status = 'blocked' AND f.blocker != #{id}
           THEN false
           ELSE true
           END
           "
    existing_friendships = User.find_by_sql(sql) unless friends_only
    sql = "SELECT u.id, u.username, u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u JOIN friendships f ON (f.user_id = #{id}
                             AND f.friend_id = u.id)
                             OR (f.friend_id = #{id} AND f.user_id = u.id)

           WHERE u.id != #{id}
           AND EXISTS(SELECT friendships.id
                      FROM friendships
                      WHERE (friendships.user_id = #{id}
                             AND friendships.friend_id = u.id)
                             OR (friendships.friend_id = #{id}
                              AND friendships.user_id = u.id))
           AND CASE
           WHEN f.status = 'blocked' AND f.blocker != #{id}
           THEN false
           WHEN f.status = 'friends'
           THEN true
           ELSE false
           END
           "
    existing_friendships ||= User.find_by_sql(sql)

    all_users << unexisting_friendships unless friends_only
    all_users << existing_friendships
    all_users.flatten!
  end

  def search(username)
    all_users = []
    sql = "SELECT u.id, u.username, u.profile_pic_file_name
           FROM users u
           WHERE u.id != #{id} AND u.username LIKE '#{username}%'
           AND NOT EXISTS(SELECT friendships.id
                          FROM friendships
                          WHERE (friendships.user_id = #{id}
                                 AND friendships.friend_id = u.id)
                                 OR (friendships.friend_id = #{id}
                                 AND friendships.user_id = u.id))"

    unexisting_friendships = User.find_by_sql(sql)
    sql = "SELECT u.id, u.username,u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u JOIN friendships f ON (f.user_id = #{id}
                                               AND f.friend_id = u.id)
                                               OR (f.friend_id = #{id}
                                               AND f.user_id = u.id)
           WHERE u.id != #{id}
                 AND u.username LIKE '#{username}%'
                 AND EXISTS(SELECT friendships.id
                            FROM friendships
                            WHERE (friendships.user_id = #{id}
                            AND friendships.friend_id = u.id)
                            OR (friendships.friend_id = #{id}
                            AND friendships.user_id = u.id))
           AND CASE
           WHEN f.status = 'blocked' AND f.blocker != #{id}
           THEN false
           ELSE true
           END"
    existing_friendships = User.find_by_sql(sql)
    all_users << unexisting_friendships
    all_users << existing_friendships
    all_users.flatten!
  end

  def relevant_posts
    sql = "SELECT u.id AS user_id, u.username,
                  p.id, p.content, p.created_at, p.post_pic_file_name
           FROM users u
           JOIN friendships f ON (f.user_id = #{id}
                                  AND f.friend_id = u.id)
                                  OR (f.friend_id = #{id}
                                  AND f.user_id = u.id)
           JOIN posts p ON p.user_id = u.id
           WHERE f.status = 'friends'
           ORDER BY p.created_at DESC"

    Post.find_by_sql(sql)
  end

  # Returns our friend user_id and user name, also returns a friendship_id and the status Only where the status is 'friends'
  # Buggy, use all_users(true) untill it gets fixed
  def all_friends
    sql = "SELECT u.id, u.username,u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u
           JOIN friendships f ON (f.user_id = #{id}
                                  AND f.friend_id = u.id)
                                  OR (f.friend_id = #{id}
                                  AND f.user_id = u.id)
           WHERE u.id != #{id} AND f.status = 'friends'"
    User.find_by_sql(sql)
  end

  # Returns true if the user has at least one friendship with status = 'friends'
  def has_friends?
    recived_sended = all_users true
    return false if recived_sended == []

    true
  end

  def blocked_me
    sql = "SELECT u.id, u.username, f.id AS friendship_id, f.status
           FROM users u JOIN friendships f ON (f.user_id = #{id}
                                               AND f.friend_id = u.id)
                                               OR (f.friend_id = #{id}
                                                AND f.user_id = u.id)
           WHERE u.id != #{id}
                 AND f.status = 'blocked'
                 AND f.blocker != #{id}"
    User.find_by_sql(sql)
  end

  # returns every user that
  def blocked
    sql = "SELECT u.id, u.username, u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u JOIN friendships f ON (f.user_id = #{id}
                                               AND f.friend_id = u.id)
                                               OR (f.friend_id = #{id}
                                               AND f.user_id = u.id)
           WHERE u.id != #{id}
                 AND f.status = 'blocked'
                 AND f.blocker = #{id}"
    User.find_by_sql(sql)
  end

  # returns the inverse_friendships with status = "waiting"
  # Or returns every frienship to confirm

  def pending
    sql = "SELECT u.id, u.username,u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u
           JOIN friendships f ON (f.friend_id = #{id}
                                  AND f.user_id = u.id)
           WHERE u.id != #{id}
           AND f.status = 'waiting' "
    pending = User.find_by_sql(sql)
    pending
  end

  def reloaded(friend_id)
    sql = "SELECT u.id, u.username,u.profile_pic_file_name, f.id AS friendship_id, f.status
           FROM users u
           JOIN friendships f ON (f.friend_id = u.id
                                  AND f.user_id = #{id})
           WHERE u.id != #{id}
                 AND (f.status = 'waiting'
                      OR f.status = 'blocked')
                 AND f.friend_id = #{friend_id}"
    pending = User.find_by_sql(sql)
    pending
  end

  def reloaded_with_existing(username)
    sql = "

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index update]
  def index
    @user = current_user
    @friends = @user.all_users true
    @posts = @user.posts.order('created_at DESC')
    @new_post = Post.new
  end

  def show
    @user = current_user
    @user ||= 'PUBLIC'
    @public_user = User.find_by(username: params[:username])
    if !@public_user.nil?
      if @user != 'PUBLIC'
        redirect_to '/404' if @user.blocked?(@public_user.id)
      end
      redirect_to user_home_path if @user == @public_user
      @posts = @public_user.posts.order('created_at DESC')
      @friends = @public_user.all_users(true)
    else
      redirect_to '/404'
    end
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    redirect_to user_home_path(@user.username) if @user.save
  end

  private

  def user_params
    params.require(:user).permit(:profile_pic)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_user.html.erb
<div class="person" id = "user_<%=user.id%>">
    <div class="person-links">
        <%=link_to image_tag(user.profile_pic.url), username_path(user.username)%>
        <h1><%= user.username.capitalize%></h1>
    </div>
    <div class="friend-links">
        
        <% if user.try(:status)%>
            <% if user.status == 'blocked' %>
                <%= link_to friendship_path(friend: user, id: user.friendship_id), method: :delete, remote: true, class: "unblock" do %>
                    <i class="material-icons">cancel</i>
                <% end %>
            <% else %>
                <%= link_to friendship_path(id: user.friendship_id, status: "blocked", from: "search"), data: {confirm: "Do you want to block #{user.username.capitalize}?"}, method: :put, remote: true,class: "blocked" do %>
                    <i class="material-icons">block</i>
                <% end %>
            <% end %>
            
            <%case user.status%>
                <%when "friends"%>
                    <%= link_to friendship_path(friend: user, id: user.friendship_id), method: :delete, remote: true,data: {confirm: "Cancel friendship with #{user.username.capitalize}?"}, class: "delete-person" do %>
                        <i class="material-icons">person_add_disabled</i>
                    <% end %>
                <%when "waiting"%>
                    <%= link_to friendship_path(friend: user, id: user.friendship_id), method: :delete, remote: true, data: {confirm: "Cancel friendship request?"}, class: "waiting" do %>
                        <i class="material-icons">access_time</i>
                    <% end %>
            <% end %>
            
        <% else %>
            <%= link_to friendships_path(friend_id: user, blocked: 'yes'), method: :post, remote: true,data: {confirm: "Do you want to block #{user.username.capitalize}?"}, class: "blocked" do %>
                <i class="material-icons">block</i>
            <% end %>
            <%= link_to friendships_path(friend_id: user), method: :post, remote: true,class: "add-person" do %>
                <i class="material-icons">person_add</i>
            <% end %>
        <% end %>
        
        
    </div>
</div>

app/views/users/index.html.erb
<div class = "hidden" id = "change">
        
    <div id = "preview" class = "preview">
        <div class="close-button" id="close-profile-pic-form">
            <i class="material-icons">close</i>
        </div>
        <%= image_tag @user.profile_pic.url , id: "image"%>
    </div>
    <div class="buttons">
        <%= form_for(@user, method: :put) do |f| %>

            <%= f.label :profile_pic do %>
                <i class="material-icons">insert_photo</i>
            <% end %>
            
            <%= f.file_field :profile_pic, style: "display: none;", onchange: 'changePicture(this)'%>
            
            <%= f.button do%>
                <i class="material-icons">navigation</i>
            <% end %>
            <%= f.submit "", style: "display:none;"%>
        <% end %>
    </div>
        
</div>
<div class = "feed-container user-show">   
    <div class = "user-info">
        
        <%=image_tag(@user.profile_pic.url, class:"profile-pic") %>
        <h1><%=@user.username.capitalize%></h1>
        <div class="change-profile-pic" id = "changeButton">
            <i class="material-icons">insert_photo</i>
        </div>
    </div>
    <main class="feed">
        <div class = "post-form">
            <%= render 'shared/post_form', personal_profile: true%>
        </div>
        <%= render @posts, has_limit: true, from_js: false%>
    </main>
    <aside class="friend-list">
        <%= render "shared/friends"%>
    </aside>

</div>
<script>
    changeButton = document.querySelector('#changeButton').addEventListener('click', ()=>{changePicForm()});
    closeButton = document.querySelector('#close-profile-pic-form').addEventListener('click', ()=> {hidePicForm()});
</script>

app/views/users/show.html.erb
<div class = "feed-container user-show">
    <div class = "user-info">

        <%=image_tag(@public_user.profile_pic.url, class:"profile-pic") %>
        <h1><%=@public_user.username.capitalize%></h1>
        
    </div>
    <main class="feed">
        <%= render @posts, has_limit: true, from_js: false%>
    </main>
    <aside class="friend-list">
        <%= render "shared/friends"%>
    </aside>

</div>