config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:update]
  resources :friendships, only: %i[create update destroy]
  resources :posts
  resources :comments

  put '/like' => 'likes#create'
  delete '/like' => 'likes#destroy'

  get '/:username' => 'users#show', :constrain => { username: /[a-zA-Z-]+/ }, as: 'username'

  get '/me/:username' => 'users#index', :constrain => { username: /[a-zA-Z-]+/ }, as: 'user_home'
  put '/me/:username' => 'users#update'

  get '/home/search' => 'search#index', as: 'search'

  get 'home/notifications' => 'search#show', as: 'notifications'
  get ':username/post/:id/edit' => 'posts#edit', as: 'post_edit'

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/views/shared/_dislike.html.erb
<%= link_to(like_path(post_id: @post, like_id: @like.id), id: "dislike_#{@like.id}", method: :delete, data: {remote: true}, class: "dislike") do%>
    <i class="material-icons">favorite</i>
<%end%>

<div id = "post-link_<%= @post.id%>"class = "post-link">
    <%= link_to  post_path(@post) do %>
        <i class="material-icons">forum</i>
    <%end%>
</div>
<div id="like-counter_<%= @post.id%>" class="likes-number">
    <h2><%= @post.likes.count > 1 ? "#{@post.likes.count} Likes" : "#{@post.likes.count} Like"%></h2>
</div>

app/views/shared/_friends.html.erb
<h1>Friends</h1>

<%us = @user if @public_user.nil?%>
<%us ||= @public_user%>

<%if us.has_friends?%>
    <%@friends.each do |friend|%>
        <div class="friend">
            <%=link_to image_tag(friend.profile_pic.url, class:"profile-pic"), username_path(friend.username) %>
            <p><%=friend.username%></p>
        </div>
    <%end%>
<%else%>
    <i>No friends yet!</i>
<%end%>

app/views/shared/_header.html.erb
    <header class = "main-header">
        <div class = "logo">
            <%= link_to image_tag("RoleandingLogo.svg", class: "logo"), root_path %>  
        </div>
        <% if user_signed_in? %>
            <div class="user-functions">
                <%= render 'shared/user_functions'%>
            </div>
        <% else %>
            <div class="login">
                <%= render 'shared/login'%>
            </div>
        <% end %>
        
            
    </header>

app/views/shared/_like.html.erb
<%= link_to(like_path(post_id: @post), id: "like_#{@post.id}", class: "like", method: :put, data: {remote: true}) do%>
    <i class="material-icons">favorite_border</i>
<%end%>
<div id = "post-link_<%= @post.id%>"class = "post-link">
    <%= link_to  post_path(@post) do %>
        <i class="material-icons">forum</i>
    <%end%>
</div>
<div id="like-counter_<%= @post.id%>" class="likes-number">
    <h2><%= @post.likes.count > 1 ? "#{@post.likes.count} Likes" : "#{@post.likes.count} Like"%></h2>
</div>

app/views/shared/_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Your email..."%>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "current-password", placeholder: "Your password..."%>
  </div>

  <div class="field">
    <%= f.submit "Sign in" , id: "sign_in"%>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@new_post, remote: personal_profile) do |f| %>
    <%=f.text_area :content, id: "new_post_text_area", autofocus:true, autocomplete: 'off', placeholder: "What are you going to share today?"%>
    <div class="left">
        <%= f.label :post_pic, class: "insert-photo" do %>
            <i class="material-icons">insert_photo</i>
        <%end%>
        <%= f.file_field :post_pic ,style: "display: none;", onchange: "readURL(this);"%>
        
        <%=f.button  id: "send_new_post",class: "create-post" do%>
            <i class="material-icons">navigation</i>
        <% end %>
    </div>
    <%= f.submit "", style: "display: none;"%>
<% end %>
<div id = "hidden" class = "hidden">
    <div class="close-button" id="close">
        <i class="material-icons">close</i>
    </div>
    <h1>IMAGE PREVIEW</h1>
    <%= image_tag "", id: "blah"%>
</div>

app/views/shared/_public_likes.html.erb
<%= link_to( root_path , class: "dislike") do%>
    <i class="material-icons">favorite</i>
<%end%>

<div id = "post-link_<%= @post.id%>"class = "post-link">
    <%= link_to  post_path(@post) do %>
        <i class="material-icons">forum</i>
    <%end%>
</div>
<div id="like-counter_<%= @post.id%>" class="likes-number">
    <h2><%= @post.likes.count > 1 ? "#{@post.likes.count} Likes" : "#{@post.likes.count} Like"%></h2>
</div>

app/views/shared/_user_functions.html.erb
<%= link_to search_path, class: 'function' do%>
    <i class="material-icons">search</i>
<%end%> 
<%= link_to user_home_path(username: current_user.username), class: 'function' do%>
    <i class="material-icons">person_outline</i>
<%end%>
<%= link_to edit_user_registration_path, class: 'function' do%>
    <i class="material-icons">edit</i>
<%end%>

<% if current_user.pending.count == 0 %>
  <%class_var = "hidden"%>
  <%p_class_var = ""%>
<% else %>
  <%class_var = "notifications"%>
<% end %>


<%= link_to notifications_path, class: "function noti", id: 'notification' do %>
    <%= content_tag(:div, content_tag(:p, current_user.pending.count, class: p_class_var), class: class_var)%>
    
    <i class="material-icons">notifications</i>
<%end%>
<%= link_to destroy_user_session_path, method: :delete, class: 'function' do%>
    <i class="material-icons">exit_to_app</i>
<%end%>